package nginx

import (
	"fmt"
	"net"
	"sort"
	"strconv"
	"strings"
)

func Render(sites []Site, acmeWebroot string) string {
	sortedSites := append([]Site(nil), sites...)
	sort.Slice(sortedSites, func(i, j int) bool {
		return sortedSites[i].Route.Domain < sortedSites[j].Route.Domain
	})

	var builder strings.Builder
	builder.WriteString("# Generated by reproxy. Do not edit by hand.\n\n")

	if len(sortedSites) == 0 {
		builder.WriteString("# No routes configured yet.\n")
		return builder.String()
	}

	for index, site := range sortedSites {
		if index > 0 {
			builder.WriteString("\n")
		}

		writeHTTPServerBlock(&builder, site, acmeWebroot)

		if site.TLSReady {
			builder.WriteString("\n")
			writeHTTPSServerBlock(&builder, site)
		}
	}

	return builder.String()
}

func writeHTTPServerBlock(builder *strings.Builder, site Site, acmeWebroot string) {
	builder.WriteString("server {\n")
	builder.WriteString("    listen 80;\n")
	builder.WriteString("    listen [::]:80;\n")
	builder.WriteString(fmt.Sprintf("    server_name %s;\n\n", site.Route.Domain))

	if strings.TrimSpace(acmeWebroot) != "" {
		builder.WriteString("    location /.well-known/acme-challenge/ {\n")
		builder.WriteString(fmt.Sprintf("        root %s;\n", acmeWebroot))
		builder.WriteString("    }\n\n")
	}

	if site.TLSReady {
		builder.WriteString("    location / {\n")
		builder.WriteString("        return 308 https://$host$request_uri;\n")
		builder.WriteString("    }\n")
		builder.WriteString("}\n")
		return
	}

	writeProxyLocation(builder, site)
	builder.WriteString("}\n")
}

func writeHTTPSServerBlock(builder *strings.Builder, site Site) {
	builder.WriteString("server {\n")
	builder.WriteString("    listen 443 ssl http2;\n")
	builder.WriteString("    listen [::]:443 ssl http2;\n")
	builder.WriteString(fmt.Sprintf("    server_name %s;\n\n", site.Route.Domain))
	builder.WriteString(fmt.Sprintf("    ssl_certificate %s;\n", site.CertPath))
	builder.WriteString(fmt.Sprintf("    ssl_certificate_key %s;\n\n", site.KeyPath))
	writeProxyLocation(builder, site)
	builder.WriteString("}\n")
}

func writeProxyLocation(builder *strings.Builder, site Site) {
	upstream := net.JoinHostPort(site.Route.TargetIP, strconv.Itoa(site.Route.TargetPort))

	builder.WriteString("    location / {\n")
	builder.WriteString(fmt.Sprintf("        proxy_pass http://%s;\n", upstream))
	builder.WriteString("        proxy_http_version 1.1;\n")
	builder.WriteString("        proxy_set_header Host $host;\n")
	builder.WriteString("        proxy_set_header X-Real-IP $remote_addr;\n")
	builder.WriteString("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
	builder.WriteString("        proxy_set_header X-Forwarded-Proto $scheme;\n")
	builder.WriteString("    }\n")
}
